import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import teachersRouter from "./teachers.js";
import sectionsRouter from "./sections.js";
import coursesRouter from "./courses.js";
import schedulesRouter from "./schedules.js";
import announcementsRouter from "./announcements.js";
import reportsRouter from "./reports.js";
import emailRouter from "./email.js";
import activityRouter from "./activity.js";
import studentsRouter from "./students.js";
import rectificacionesRouter from "./rectificaciones.js";
import seguridadDocentesRouter from "./seguridad-docentes.js";
import seguridadIncidenciasRouter from "./seguridad-incidencias.js";
import sinMatriculaRouter from "./sin-matricula.js";
import sinVacanteRouter from "./sin-vacante.js";
import delegadosRouter from "./delegados.js";
import asistenciaRouter from "./asistencia.js";
import asistenciaPlanillasRouter from "./asistencia-planillas.js";
import studentProblemsRouter from "./student-problems.js";
import sharedStateRouter from "./shared-state.js";
import justificacionesRouter from "./justificaciones.js";

const router = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/teachers", teachersRouter);
router.use("/sections", sectionsRouter);
router.use("/courses", coursesRouter);
router.use("/schedules", schedulesRouter);
router.use("/announcements", announcementsRouter);
router.use("/reports", reportsRouter);
router.use("/email", emailRouter);
router.use("/activity", activityRouter);
router.use("/students", studentsRouter);
router.use("/rectificaciones", rectificacionesRouter);
router.use("/seguridad-docentes", seguridadDocentesRouter);
router.use("/seguridad-incidencias", seguridadIncidenciasRouter);
router.use("/sin-matricula", sinMatriculaRouter);
router.use("/sin-vacante", sinVacanteRouter);
router.use("/delegados", delegadosRouter);
router.use("/asistencia", asistenciaRouter);
router.use("/asistencia-planillas", asistenciaPlanillasRouter);
router.use("/student-problems", studentProblemsRouter);
router.use("/shared-state", sharedStateRouter);
router.use("/justificaciones", justificacionesRouter);

export default router;
